name: demo
channels:
  - defaults
  - bioconda
  - conda-forge
  # - cctbx202112
  # - cctbx202105
  # - cctbx202008
dependencies:
  # - jinja2=3.0.3
  # - htslib>=1.10.2,<1.11.0a0|>=1.12,<1.13.0a0|>=1.14,<1.15.0a0|>=1.9,<1.10.0a0
  # - openjdk=11.0.9.1
  # - dnaio=0.7.1
  # - matplotlib-base=3.5.1
  # - openssl=1.1.1l
  # - networkx=2.7.1
  # - libgcc-ng=11.2.0
  # - font-ttf-dejavu-sans-mono=2.37
  # - ld_impl_linux-64=2.36.1
  # - libffi=3.3
  # - sqlite=3.37.0
  # - markdown=3.3.6
  # - libstdcxx-ng=11.2.0
  # - future=0.18.2
  # - pip=21.2.4
  # - setuptools=58.0.4
  # - pyyaml=6.0
  # - fontconfig=2.13.1
  # - python_abi=3.8*
  # - click=8.0.4
  # - ucsc-bigwigsummary=377
  # - requests=2.27.1
  # - perl=5.32.1
  # - xopen=1.4.0
  # - zlib=1.2.11
  # - perl-module-build=0.4231
  # - rich=11.2.0
  # - bioconductor-ebseq=1.34.0
  # - simplejson=3.17.6
  # - lzstring=1.0.4
  # - r-base=4.1.2
  # - tk>=8.6.12
  # - readline=8.1
  # - coloredlogs=15.0.1
  # - spectra=0.0.11
  # - ncurses=6.3
  # - bioconductor-biobase=2.54.0
  - samtools=1.15
  - cutadapt=3.7
  - fastqc=0.11.9
  - trim-galore=0.6.7
  - multiqc=1.12
  - star=2.7.10a
  - rsem=1.3.3
