name: demo
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - samtools=1.15
  - cutadapt=3.7
  - fastqc=0.11.9
  - trim-galore=0.6.7
  - multiqc=1.12
  - star=2.7.0b
  - rsem=1.3.3
